CREATE TABLE IF NOT EXISTS users (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username TEXT UNIQUE NOT NULL,
	password_hash TEXT NOT NULL,
	is_admin BOOLEAN DEFAULT 0,
	is_disabled BOOLEAN DEFAULT 0,
	created_at DATETIME NOT NULL
);
